# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push

env:
  github_username: rhandarov
  github_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run snyk
      working-directory: ${{github.workspace}}/app
      run: |
        npm install -g snyk
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk test

  Edit-or-config-checks:
    runs-on: ubuntu-latest
    needs: [security]
    steps:
    - name: Cloning repo
      uses: actions/checkout@v4
    - name: Running checks
      uses: editorconfig-checker/action-editorconfig-checker@main
    - run: editorconfig-checker

  Markdon-checks:
    runs-on: ubuntu-latest
    needs: [security]
    steps:
    - name: Clonning repo
      uses: actions/checkout@v4
    - name: Run markdown lint
      uses: nosborn/github-action-markdown-cli@v3.5.0
      with:
        files: .
        config_file: .markdownlint.yaml
        dot: true

  Linting:
    runs-on: ubuntu-latest
    needs: [security]
    steps:
    - name: Donwload code
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: Run lintitng
      uses: super-linter/super-linter/slim@v7
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISABLE_ERRORS: true
# This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: gradle:6-jdk11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone down repository
        uses: actions/checkout@v4

      - name: Build application
        run: ci/build-app.sh

      - name: Test application
        run: ci/unit-test-app.sh

      - name: Upload repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true

  Sonar-cloud-check:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - name: Cloning repo
      uses: actions/checkout@v4
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6.0.0  # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Docker-Image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [Build]
    steps:
    - name: Download code
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: Build docker
      run: bash ci/build-docker.sh
    - name: Push docker
      run: bash ci/push-docker.sh

  Component-test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [Docker-Image]
    steps:
    - name: Download code
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: Execute component test
      run: bash ci/component-test.sh

  Performance-test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [Docker-Image]
    steps:
    - name: Download code
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: Execute performance test
      run: bash ci/performance-test.sh

